DIMENTION = 4
THRESHOLD_HEIGHT = 1
USING_HEIGHT = 1
VIVALDI_LOCAL_ERROR = 1.5

'''USED IN VivaldiNeighborManager'''
VIVALDI_MAX_NEIGHBOR_NUM = 100
VIVALDI_SELECTED_NEIGHBOR_NUM = 32

'''USED IN VivaldiNCClient'''
CE = 0.25
CC = 0.25

'''USED IN TWISTED'''
ALGORITHM = "Vivaldi"
LOOPTIME = 1
PINGMETHOD = "TCP"
PINGPORT = 11232
PINGTIMEOUT = 5
PINGNUM = 5
PINGBYTES = 56
GOSSIPPORT = 11233
NCPORT = 11234
GOSSIPTIMEOUT = 2
NCTIMEOUT = 2